### ISSUE TITLE
ImageRead for OLED and TFT

### ISSUE THREAD

**Issue by marcwolf1960** [adafruit/Adafruit_ImageReader#2]
I have seen a lot of different modules - some cater only for OLED, others cater only for TFT.
I'm trying to help some people with a simple project so they can swap between TFT or OLED depending on cost.

If you could include an example for a SSD1351 that would be really great. 
Target processor is the Huzzah-32  (ESP32)

Marc

**Comment by ladyada** [comment]
should be basically the same as
https://github.com/adafruit/Adafruit_ImageReader/tree/master/examples
do you want to try to make an eample and submit it as a PR :)

**Comment by ladyada** [comment]
@makermelissa you can take a look at this too!

**Comment by marcwolf1960** [comment]
Hi.. I will be programming using Arduino code only.. Not Python.

I guess what I am trying to do is this

#IF TFT THEN
   TFT_Lib Display;
#ELSE
  OLED_Lib Display;
#END IF

Display.Clear;
Display.Draw_BMP( .....)

So the calling code is the same however the libraries will change. 
Dave

**Comment by ladyada** [comment]
hiya no need, just clone of of the examples https://github.com/adafruit/Adafruit_ImageReader
replace it with the OLED display and submit it. its arduino only in this repo :)
