### ISSUE TITLE
SSD1331 ESP32

### ISSUE THREAD

**Issue by amirjak** [adafruit/Adafruit_ImageReader#29]
- Arduino board:  **DOIT ESP32 DEVKIT V1**

- Arduino IDE version (found in Arduino -> About Arduino menu):  **1.8.12**

I USE examples/BreakoutSSD1331/ For **esp32 with the SD Card Module**

![01](https://user-images.githubusercontent.com/46311349/85512742-77dda300-b60f-11ea-99f9-0fb97e24aa4d.jpg)

**During upload sketch this error happened** 
**Please guide me**

Arduino: 1.8.12 (Windows 10), Board: "DOIT ESP32 DEVKIT V1, 80MHz, 921600, None"

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp: In member function 'virtual void Adafruit_FlashTransport_SPI::begin()':

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:39:16: error: **'OUTPUT' was not declared in this scope**

   pinMode(_ss, OUTPUT);

                ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:39:22: error: 'pinMode' was not declared in this scope

   pinMode(_ss, OUTPUT);

                      ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:40:21: error: 'HIGH' was not declared in this scope

   digitalWrite(_ss, HIGH);

                     ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:40:25: error: 'digitalWrite' was not declared in this scope

   digitalWrite(_ss, HIGH);

                         ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp: In member function 'virtual void Adafruit_FlashTransport_SPI::setClockSpeed(uint32_t)':

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:46:36: error: 'MSBFIRST' was not declared in this scope

   _setting = SPISettings(clock_hz, MSBFIRST, SPI_MODE0);

                                    ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp: In member function 'virtual bool Adafruit_FlashTransport_SPI::runCommand(uint8_t)':

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:50:21: error: 'LOW' was not declared in this scope

   digitalWrite(_ss, LOW);

                     ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:50:24: error: 'digitalWrite' was not declared in this scope

   digitalWrite(_ss, LOW);

                        ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:56:21: error: 'HIGH' was not declared in this scope

   digitalWrite(_ss, HIGH);

                     ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp: In member function 'virtual bool Adafruit_FlashTransport_SPI::readCommand(uint8_t, uint8_t*, uint32_t)':

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:63:21: error: 'LOW' was not declared in this scope

   digitalWrite(_ss, LOW);

                     ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:63:24: error: 'digitalWrite' was not declared in this scope

   digitalWrite(_ss, LOW);

                        ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:72:21: error: 'HIGH' was not declared in this scope

   digitalWrite(_ss, HIGH);

                     ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp: In member function 'virtual bool Adafruit_FlashTransport_SPI::writeCommand(uint8_t, const uint8_t*, uint32_t)':

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:80:21: error: 'LOW' was not declared in this scope

   digitalWrite(_ss, LOW);

                     ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:80:24: error: 'digitalWrite' was not declared in this scope

   digitalWrite(_ss, LOW);

                        ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:89:21: error: 'HIGH' was not declared in this scope

   digitalWrite(_ss, HIGH);

                     ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp: In member function 'virtual bool Adafruit_FlashTransport_SPI::eraseCommand(uint8_t, uint32_t)':

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:96:21: error: 'LOW' was not declared in this scope

   digitalWrite(_ss, LOW);

                     ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:96:24: error: 'digitalWrite' was not declared in this scope

   digitalWrite(_ss, LOW);

                        ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:107:21: error: 'HIGH' was not declared in this scope

   digitalWrite(_ss, HIGH);

                     ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp: In member function 'virtual bool Adafruit_FlashTransport_SPI::readMemory(uint32_t, uint8_t*, uint32_t)':

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:114:21: error: 'LOW' was not declared in this scope

   digitalWrite(_ss, LOW);

                     ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:114:24: error: 'digitalWrite' was not declared in this scope

   digitalWrite(_ss, LOW);

                        ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:129:21: error: 'HIGH' was not declared in this scope

   digitalWrite(_ss, HIGH);

                     ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp: In member function 'virtual bool Adafruit_FlashTransport_SPI::writeMemory(uint32_t, const uint8_t*, uint32_t)':

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:137:21: error: 'LOW' was not declared in this scope

   digitalWrite(_ss, LOW);

                     ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:137:24: error: 'digitalWrite' was not declared in this scope

   digitalWrite(_ss, LOW);

                        ^

C:\Users\ali\Documents\Arduino\libraries\Adafruit_SPIFlash\src\spi\Adafruit_FlashTransport_SPI.cpp:152:21: error: 'HIGH' was not declared in this scope

   digitalWrite(_ss, HIGH);

                     ^

exit status 1
Error compiling for board DOIT ESP32 DEVKIT V1.
Invalid library found in C:\Users\ali\Documents\Arduino\libraries\Adafruit_ImageReader_Library: no headers files (.h) found in C:\Users\ali\Documents\Arduino\libraries\Adafruit_ImageReader_Library
Invalid library found in C:\Users\ali\Documents\Arduino\libraries\Adafruit_ImageReader_Library: no headers files (.h) found in C:\Users\ali\Documents\Arduino\libraries\Adafruit_ImageReader_Library

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by ladyada** [comment]
something is wrong with your library installation or IDE setup - please post in the DOIT or esp32 forums for help!
