### ISSUE TITLE
ShieldILI9341 takes 88% of storage space on Arduino UNO

### ISSUE THREAD

**Issue by romton843** [adafruit/Adafruit_ImageReader#33]
Hi the ShieldILI9341 sketch example, the sketch uses a lot of storage space and therefore I can't add the rest of my code.
Is it normal it takes 88% of an Arduino UNO storage space?
I just want to load one picture to an Adafruit 2.8" TFT touchscreen...
Do I just need to upgrade to a Metro M0 Express or is there a way to reduce the size of this sketch? 

- Arduino board: Adafruit Metro 328
- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.13 (Windows Store 1.8.42.0)

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too): Just compiling the sketch

**Comment by ladyada** [comment]
yeah the code for UNO has grown and grown with the compiler, we really recommend M0 at this point.
