### ISSUE TITLE
Examples don't compile any more with the new version 2.5.2 ?

### ISSUE THREAD

**Issue by Greece2** [adafruit/Adafruit_ImageReader#39]
It seems the non of the examples that come with the lib compiles any more since the new version of the lib is available.
Tried all kind of boards, always get (among lots of warnings...)
> no matching function for call to 'Adafruit_ImageReader::Adafruit_ImageReader(SdFat&)'

(Board Mega 2560, Example ShieldIlI9341, ImageReader lib version 2.5.2, SDfat 2.0.4)

Any idea how to fix that ?
Thanks and stay safe !

**Comment by ladyada** [comment]
the current examples all compile just fine. 
you can verify it with the CI output
https://github.com/adafruit/Adafruit_ImageReader/runs/1718328319?check_suite_focus=true
you could make sure you're running all the latest libraries!
