### ISSUE TITLE
Error compiling for board Adafruit ESP32 Feather.

### ISSUE THREAD

**Issue by Cheapy-D** [adafruit/Adafruit_ImageReader#51]
I went to version 1.0.2 and it works fine but If there's benefits to the newer version then of course I wanna use it. I posted on the forums about it https://forums.adafruit.com/viewtopic.php?f=47&t=188030 that basically explains it the best. I'm using the example sketch have these versions:
Adafruit GFX Library - 1.10.14
Adafruit  ILI9341 - 1.5.10
SdFat Adafruit Fork - 1.5.1
Adafruit SPIFlash - 3.9.1
Adafruit ImageReader - 2.8.0
and I get this error:

`Arduino: 1.8.17 Hourly Build 2021/09/06 02:33 (Windows 10), Board: "Adafruit ESP32 Feather, 80MHz, 921600, None, Default"

C:\Users\Cheapy\Documents\Arduino\libraries\Adafruit_SPIFlash\src\esp32\Adafruit_FlashTransport_ESP32.cpp: In member function 'SPIFlash_Device_t* Adafruit_FlashTransport_ESP32::getFlashDevice()':

C:\Users\Cheapy\Documents\Arduino\libraries\Adafruit_SPIFlash\src\esp32\Adafruit_FlashTransport_ESP32.cpp:62:3: error: 'esp_flash_t' was not declared in this scope

   esp_flash_t const *flash = _partition->flash_chip;

   ^

C:\Users\Cheapy\Documents\Arduino\libraries\Adafruit_SPIFlash\src\esp32\Adafruit_FlashTransport_ESP32.cpp:63:36: error: 'flash' was not declared in this scope

   _flash_device.manufacturer_id = (flash->chip_id >> 16);

                                    ^

exit status 1

Error compiling for board Adafruit ESP32 Feather.`

**Comment by makermelissa** [comment]
I just tried compiling on Arduino 1.8.19 with the latest ImageReader and it compiled successfully, so the library itself is working. You may want to try a later Arduino and Make sure your ESP32 Board (through Board Manager) is up to date.
